/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.DatabaseConnection;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author macarena
 */
public class LoginView extends javax.swing.JFrame {

    private URL imgAceptarURL;
    private URL imgCancelarURL;
    private RegistroView registroView;
    private DatabaseConnection databaseConnection;
    private UsuarioDAO usuarioDAO;
    private int intentos;

    public LoginView(DatabaseConnection databaseConnection) {
        initComponents();
        this.usuarioDAO = new UsuarioDAO(databaseConnection);
        this.databaseConnection=databaseConnection;
        setFrame();
    }

    private void setFrame() {
        this.imgAceptarURL = this.getClass().getResource("/images/aceptar.png");
        this.imgCancelarURL = this.getClass().getResource("/images/cancelar.png");
        this.botonAceptar.setIcon(new ImageIcon(imgAceptarURL));
        this.botonCancelar.setIcon(new ImageIcon(imgCancelarURL));
        
        this.labelRegistro.setText("<HTML> <FONT color=\"#000099\"><U>¿Todavía no te has registrado?</U></FONT> </HTML>");
        this.labelRegistro.setToolTipText("Pulsa para registrarte");
        this.labelRegistro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        botonAceptar = new javax.swing.JButton();
        labelRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        botonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonCancelarKeyReleased(evt);
            }
        });

        jPasswordField1.setEchoChar('\u2688');

        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        botonAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonAceptarKeyReleased(evt);
            }
        });

        labelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  // Métodos para acceder a los datos ingresados por el usuario

    public String getLogin() {
        return this.jTextField1.getText();
    }

    public String getPassword() {
        return new String(this.jPasswordField1.getPassword());
    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String login = getLogin();
        String passwd = getPassword();

        // Consultamos si el usuario con ese login existe en la BD
        Usuario usuario = usuarioDAO.getUsuarioByLogin(login);
        if (usuario != null) {
            if (usuario.getBlocked() == 1) {
                JOptionPane.showMessageDialog(this, "Usuario bloqueado", "Acceso", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // El usuario no está bloqueado
            if (usuario.getPassword().equals(passwd)) {
                try {
                    JOptionPane.showMessageDialog(this, "Bienvenido!!", "Acceso", JOptionPane.INFORMATION_MESSAGE);
                    Desktop.getDesktop().browse(new URI("http://www.gregoriofer.com"));
                } catch (URISyntaxException | IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Acceso", JOptionPane.WARNING_MESSAGE);
                this.intentos++;
                if (this.intentos == DatabaseConnection.UMBRAL) {
                    usuario.setBlocked(1);
                    if (usuarioDAO.bloquearUsuario(usuario)) {
                        JOptionPane.showMessageDialog(this, "Usuario bloqueado", "Acceso", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario no registrado en la base de datos", "Acceso", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void labelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistroMouseClicked
        registroView = new RegistroView(this,databaseConnection);
        registroView.setVisible(true);
    }//GEN-LAST:event_labelRegistroMouseClicked

    private void botonAceptarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAceptarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.botonAceptar.doClick();
        }
    }//GEN-LAST:event_botonAceptarKeyReleased

    private void botonCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonCancelarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.botonCancelar.doClick();
        }
    }//GEN-LAST:event_botonCancelarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelRegistro;
    // End of variables declaration//GEN-END:variables
}
