/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.text.Format;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import model.RespuestasDAO;



/**
 *
 * @author jovcubni
 */
public class ResultadosView extends javax.swing.JDialog {
    
    private RespuestasDAO respuestasDAO;


    /**
     * Creates new form ResultadosView
     */
    public ResultadosView(java.awt.Frame parent, boolean modal, RespuestasDAO respuestasDAO ) {
        super(parent, modal);
        initComponents();
        this.respuestasDAO = respuestasDAO;
        setFreim();
    }

    ResultadosView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

    
    public void setFreim(){
        DateTimeFormatter dtf = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.SHORT);
        String tituloVentana = dtf.format(LocalDateTime.now());
        this.setTitle(tituloVentana);
        this.jEditorPane1.setContentType("text/html");
        this.jEditorPane1.setEditable(false);
        this.jEditorPane1.getCaret().deinstall(jEditorPane1);
        this.setLocationRelativeTo(null);
        this.setMinimumSize(new Dimension (300,200)); 
        this.setPreferredSize(new Dimension (300,200));

         calcularRespuesta();
        
    }
    
        ///////////////////////
        //Formateo porcentaje//
        ///////////////////////
   
    private void calcularRespuesta() {
    try {
        int total = respuestasDAO.contarTodas();
        int nY = respuestasDAO.contarYes();
        int nN = respuestasDAO.contarNo();
        int nNSNC = respuestasDAO.contarNsNc();

        // Calcular porcentaje
        NumberFormat nf = NumberFormat.getPercentInstance();
        nf.setMaximumFractionDigits(2);

        String html = "<html><body>";
        html += "<h2>Resultados de la encuesta</h2>";
        html += "<p><b>Total respuestas:</b> " + total + "</p>";
        html += "<p><b>Sí:</b> " + nY + " (" + nf.format((double)nY / total) + ")</p>";
        html += "<p><b>No:</b> " + nN + " (" + nf.format((double)nN / total) + ")</p>";
        html += "<p><b>NS/NC:</b> " + nNSNC + " (" + nf.format((double)nNSNC / total) + ")</p>";
        html += "</body></html>";

        jEditorPane1.setText(html);
    } catch (Exception e) {
        jEditorPane1.setText("<html><body><p>Error al cargar los resultados.</p></body></html>");
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
