/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.DatabaseConnection;
import model.Respuesta;
import model.RespuestasDAO;


/**
 *
 * @author jovcubni
 */
public class VotarView extends javax.swing.JFrame {

    
     private DatabaseConnection databaseConnection; // Se declara como instancia, no estática3
     private RespuestasDAO respuestasDAO;

    /**
     * Creates new form BotarView
     * @param databaseConnection La conexión a la base de datos
     */
    public VotarView(DatabaseConnection databaseConnection, RespuestasDAO respuestasDAO) {
        this.databaseConnection = databaseConnection; // Guarda la conexión
        initComponents(); // Inicializa los componentes gráficos
        this.respuestasDAO = respuestasDAO;
        setFrame();
    }

    public ButtonGroup grupoOpciones = new ButtonGroup();
    public void setFrame(){
        this.setName("Encuesta");
        this.setLocationRelativeTo(null);
        //Butongrup
        grupoOpciones.add(Si); 
        grupoOpciones.add(no);
        grupoOpciones.add(nsnc);

        //
        this.setMinimumSize(new Dimension(500, 250));
        this.pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPregunta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        votar = new javax.swing.JButton();
        resultados = new javax.swing.JButton();
        PanelOpciones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Si = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        nsnc = new javax.swing.JRadioButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        no = new javax.swing.JRadioButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        PanelContenedor.setForeground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.BorderLayout());

        PanelPregunta.setPreferredSize(new java.awt.Dimension(544, 32));
        PanelPregunta.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Te gusta programar?");
        PanelPregunta.add(jLabel1, java.awt.BorderLayout.CENTER);

        PanelContenedor.add(PanelPregunta, java.awt.BorderLayout.PAGE_START);

        PanelBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 7));

        votar.setText("Votar");
        votar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                votarMouseClicked(evt);
            }
        });
        votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votarActionPerformed(evt);
            }
        });
        votar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                votarKeyReleased(evt);
            }
        });
        PanelBotones.add(votar);

        resultados.setText("Resultados de la encuesta");
        resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosActionPerformed(evt);
            }
        });
        resultados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultadosKeyReleased(evt);
            }
        });
        PanelBotones.add(resultados);

        PanelContenedor.add(PanelBotones, java.awt.BorderLayout.PAGE_END);

        PanelOpciones.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler1);

        Si.setText("SI");
        Si.setHideActionText(true);
        Si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Si.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(Si);
        jPanel2.add(filler2);

        PanelOpciones.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(filler4);

        nsnc.setText("NS/NC");
        nsnc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nsnc.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel3.add(nsnc);
        jPanel3.add(filler3);

        PanelOpciones.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler6);

        no.setText("NO");
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel4.add(no);
        jPanel4.add(filler5);

        PanelOpciones.add(jPanel4);

        PanelContenedor.add(PanelOpciones, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void votarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_votarKeyReleased
        // TODO add your handling code here:..
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            this.votar.doClick();
        }
    }//GEN-LAST:event_votarKeyReleased

    private void resultadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadosKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            this.resultados.doClick();
        }
    }//GEN-LAST:event_resultadosKeyReleased

    // Boton Votar
    private void votarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votarMouseClicked
        //Si no vota --> Mensaje
        if (this.grupoOpciones.getSelection()== null){
            JOptionPane.showMessageDialog(this, "Tienes que aceptar una opcion");
        }else{ //Responde --> Guarfar Opciones
            Respuesta respuesta = new Respuesta();
            if (this.Si.isSelected()){
                respuesta.setYes(1);
                respuesta.setNo(0);
                respuesta.setNs_nc(0);
            }else if (this.no.isSelected()){
                respuesta.setYes(0);
                respuesta.setNo(1);
                respuesta.setNs_nc(0);
            }else if (this.nsnc.isSelected()){
                respuesta.setYes(0);
                respuesta.setNo(0);
                respuesta.setNs_nc(1);
            }
            
           if (respuestasDAO.insertRespuestas(respuesta)) {
                JOptionPane.showMessageDialog(this, "Gracias por votar");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar tu voto");
            }
 
            grupoOpciones.clearSelection(); 
        }
        
    }//GEN-LAST:event_votarMouseClicked

    private void resultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosActionPerformed
        // TODO add your handling code here:
        ResultadosView resultadosView = new ResultadosView(this, true);
        resultadosView.setFreim();
        resultadosView.setVisible(true);

    }//GEN-LAST:event_resultadosActionPerformed

    private void votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelPregunta;
    private javax.swing.JRadioButton Si;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton nsnc;
    private javax.swing.JButton resultados;
    private javax.swing.JButton votar;
    // End of variables declaration//GEN-END:variables
}
