/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import model.DatabaseConnection;

/**
 *
 * @author jovcubni
 */
public class VotarView extends javax.swing.JFrame {

    
     private DatabaseConnection databaseConnection; // Se declara como instancia, no estática

    /**
     * Creates new form BotarView
     * @param databaseConnection La conexión a la base de datos
     */
    public VotarView(DatabaseConnection databaseConnection) {
        this.databaseConnection = databaseConnection; // Guarda la conexión
        initComponents(); // Inicializa los componentes gráficos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPregunta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelOpciones = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        PanelContenedor.setForeground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.BorderLayout());

        PanelPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        PanelPregunta.setPreferredSize(new java.awt.Dimension(544, 32));
        PanelPregunta.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Te gusta programar?");
        PanelPregunta.add(jLabel1, java.awt.BorderLayout.CENTER);

        PanelContenedor.add(PanelPregunta, java.awt.BorderLayout.PAGE_START);

        PanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        PanelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        PanelBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 7));

        jButton1.setText("Votar");
        PanelBotones.add(jButton1);

        jButton2.setText("Resultados de la encuesta");
        PanelBotones.add(jButton2);

        PanelContenedor.add(PanelBotones, java.awt.BorderLayout.PAGE_END);

        PanelOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102)));
        PanelOpciones.setLayout(new java.awt.GridLayout(0, 1));

        jRadioButton1.setText("SI");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelOpciones.add(jRadioButton1);

        jRadioButton2.setText("NO");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelOpciones.add(jRadioButton2);

        jRadioButton3.setText("NS/NC");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelOpciones.add(jRadioButton3);

        PanelContenedor.add(PanelOpciones, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelPregunta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
