/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Eejercicios;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author jovcubni
 */
public class Datos extends javax.swing.JFrame {

    public static int[] array = {1,2,3,4,5,6,7,8,9,10};
    
    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonCrearArray = new javax.swing.JButton();
        BotonSumaPares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonCrearArray.setText("Generar array");
        BotonCrearArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearArrayActionPerformed(evt);
            }
        });

        BotonSumaPares.setText("Suma Pares");
        BotonSumaPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaParesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BotonCrearArray))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(BotonSumaPares)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonCrearArray)
                .addGap(18, 18, 18)
                .addComponent(BotonSumaPares)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearArrayActionPerformed
        // TODO add your handling code here:
        int tamanio = 10;
        array= new int[tamanio]; //llamamos al array, como se de un objeto se tratase
            System.out.println("El Array creado tiene "+array.length+" valores");
            JOptionPane.showMessageDialog(this, "El Array creado tiene "+array.length+" valores");
    //        mostrarArray();
    //        Arrays.fill(alturas, -1);
    //        mostrarArray();

            rellenarArray();
            mostrarArray();
        
    }//GEN-LAST:event_BotonCrearArrayActionPerformed

    private void BotonSumaParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaParesActionPerformed
        // TODO add your handling code here:
        sumapares();
    }//GEN-LAST:event_BotonSumaParesActionPerformed
 
    private void sumapares(){
        int sumaPares=0;
        for (int i=0; i<array.length; i+=2){
        sumaPares+=array[i];
        System.out.println("El "+ array[i]+ " es par y esta en la posicion "+i );
        
        }
        System.out.println("Suma = "+sumaPares);
    }
    
    // Aleatorio del 1 al 50
    public void rellenarArray(){
        Random r =new Random();
        for (int i = 0; i<array.length; i++){
            array [i] = r.nextInt(1,51);
        }
    }
    public void mostrarArray(){
        for (int i = 0; i<array.length; i++){
            System.out.println( array[i]);
            JOptionPane.showMessageDialog(this, "El balor del array crreado es " + array[i]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearArray;
    private javax.swing.JButton BotonSumaPares;
    // End of variables declaration//GEN-END:variables
}
