/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.practica3.vista;

import com.practica3.controlador.CSVajustes;
import com.practica3.modelo.Employees;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class view extends javax.swing.JFrame {

    public DefaultListModel<Employees> modeloLista = new DefaultListModel<>();

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        setFreim();
    }

    public void setFreim() {
        this.setLocationRelativeTo(null);
        ListaDatos.setModel(modeloLista);
        this.setTitle("Empleados-HR");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button1 = new java.awt.Button();
        PanelSuperior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        PanelInferior = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCargarDAtos = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonAñadirDatos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PanelInfo = new javax.swing.JPanel();
        marjen3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        marjen1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        marjen2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDatos = new javax.swing.JList();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar por"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("ID");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Apellido");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PanelSuperior, java.awt.BorderLayout.PAGE_START);

        PanelInferior.setLayout(new java.awt.BorderLayout());

        PanelBotones.setLayout(new java.awt.GridLayout(0, 1, 10, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        PanelBotones.add(jPanel2);

        BotonCargarDAtos.setText("Cargar datos");
        BotonCargarDAtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarDAtosActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonCargarDAtos);

        BotonBuscar.setText("Busqueda");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonBuscar);

        BotonAñadirDatos.setText("Añadir + datos");
        BotonAñadirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirDatosActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonAñadirDatos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        PanelBotones.add(jPanel3);

        PanelInferior.add(PanelBotones, java.awt.BorderLayout.LINE_END);

        PanelInfo.setLayout(new java.awt.BorderLayout());
        PanelInfo.add(marjen3, java.awt.BorderLayout.PAGE_END);
        PanelInfo.add(marjen1, java.awt.BorderLayout.LINE_END);
        PanelInfo.add(marjen2, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setViewportView(ListaDatos);

        PanelInfo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelInferior.add(PanelInfo, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelInferior, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Clases que necesitamos accesivles
    protected File archivoEmpleado;
    protected List<Employees> empleados;

    private void BotonCargarDAtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarDAtosActionPerformed

        // Crear un objeto JFileChooser para permitir al usuario seleccionar un archivo desde el sistema
        JFileChooser archivo = new JFileChooser();
        // Mostrar el cuadro de diálogo para abrir archivo
        int resultado = archivo.showOpenDialog(this);
        // Verificamos si el usuario ha seleccionado un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo que el usuario seleccionó
            archivoEmpleado = archivo.getSelectedFile();
            empleados = CSVajustes.leerEmpleadosDesdeCSV(archivoEmpleado);

            // Recorrer la lista de empleados y mostrarlos 
            for (Employees emp : empleados) {
                modeloLista.addElement(emp);
            }
        }


    }//GEN-LAST:event_BotonCargarDAtosActionPerformed


    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:

        if (archivoEmpleado == null) {
            JOptionPane.showMessageDialog(this, "No hay ningun fichero csv cargado", "info", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                String opcion = JOptionPane.showInputDialog("Introduce id del empleado");
                int idBusco = Integer.parseInt(opcion);
                boolean encontrado = false;
                for (Employees emp : empleados) {
                    if (emp.getId() == idBusco) {
                        JOptionPane.showMessageDialog(this, emp.toString(), "Empleado Encontrado", JOptionPane.INFORMATION_MESSAGE);
                        encontrado = true;
                        break;
                    }

                }

                if (!encontrado) {
                    JOptionPane.showMessageDialog(this, "Id no encontrado", "no encontrado", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El id es numérico", "error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonAñadirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirDatosActionPerformed
        // TODO add your handling code here:
        if (archivoEmpleado == null) {
            JOptionPane.showMessageDialog(this, "Es necesario que haya un fichero csv cargado para agregarle otro", "info", JOptionPane.ERROR_MESSAGE);
        } else {
            //Guardamos el nuevo fichero que añadira los datos al orijinal
            JFileChooser archivoAñado = new JFileChooser();
            // Mostrar el cuadro de diálogo para abrir archivo
            int resultado = archivoAñado.showOpenDialog(this);
            // Verificamos si el usuario ha seleccionado un archivo
            if (resultado == JFileChooser.APPROVE_OPTION) {
                // añadir al archivo orijinal los nuevos datos
                File nuevosDatos = archivoAñado.getSelectedFile();
                empleados = CSVajustes.añadirDatos(archivoEmpleado,nuevosDatos);

            }
        }
    }//GEN-LAST:event_BotonAñadirDatosActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadirDatos;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCargarDAtos;
    private javax.swing.JList ListaDatos;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelSuperior;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.Box.Filler marjen1;
    private javax.swing.Box.Filler marjen2;
    private javax.swing.Box.Filler marjen3;
    // End of variables declaration//GEN-END:variables
}
