/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package t8.arrays;

import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author jovcubni
 */
public class ejemplo1 extends javax.swing.JFrame {

   private int[] alturas; // asi es como se declara un array para, en este caso, almacenar alturas.
    
    /**
     * Creates new form Ejemplo1
     */
    public ejemplo1() {
        initComponents();
        
        this.setTitle("Primer ejemplo de arrays");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NumElementos = new javax.swing.JTextPane();
        BotonCrear = new javax.swing.JButton();
        alturaMedia = new javax.swing.JButton();
        alturaMaxMin = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de elementos");

        jScrollPane1.setViewportView(NumElementos);

        BotonCrear.setText("Creacion de atributos");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        alturaMedia.setText("Altura Media");
        alturaMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaMediaActionPerformed(evt);
            }
        });

        alturaMaxMin.setText("Altura maxima y minima");
        alturaMaxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaMaxMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonCrear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(alturaMedia)
                        .addGap(39, 39, 39)
                        .addComponent(alturaMaxMin)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonCrear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaMedia)
                    .addComponent(alturaMaxMin))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        // creamos el array de alturas
        int tamanio=Integer.parseInt( this.textFieldNumElementos.getText());
        alturas= new int[tamanio]; //llamamos al array, como se de un objeto se tratase
        System.out.println("Array creado de tamanio "+alturas.length);
//        mostrarArray();
//        Arrays.fill(alturas, -1);
//        mostrarArray();
        
        rellenarArray();
        mostrarArray();
    }//GEN-LAST:event_BotonCrearActionPerformed

    private void BotonAlturaMediaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        int total=0; //acumula las alturas
        int contador=0; //contabiliza las alturas
        for(int i=0; i<alturas.length; i++){
            if(alturas[i] !=0){
                contador++;
                total+= alturas.length;
            }
        }
        double media= total/contador;
        System.out.println("La media es: "+media);
    }                                                

    private void BotonMinMaxActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        int min = 0;
        int max = 0;
        int actual=alturas.length;
        
        hacerMin();
        hacerMax();
        
    }                                           

    private void hacerMin(){
        
    }
    
    private void hacerMax(){
        
    }
    
     //Llena el array con alturas entre 10 y 300.
    private void rellenarArray(){
        Random r = new Random();
        for(int i=0; i<alturas.length; i++){
            alturas[i]=r.nextInt(10,301);
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void alturaMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaMediaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_alturaMediaActionPerformed

    private void alturaMaxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaMaxMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaMaxMinActionPerformed

  //Muestra el contenido del Array 
    private void mostrarArray(){
        for(int i=0; i<alturas.length; i++){
            System.out.println("Posicion " +i+ ":" +alturas[i]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejemplo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrear;
    private javax.swing.JTextPane NumElementos;
    private javax.swing.JButton alturaMaxMin;
    private javax.swing.JButton alturaMedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
