/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.crud;

import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author macarena
 */
public class EjemploCRUD extends javax.swing.JFrame {

    public static String bd = "ejemplo";
    public static String urlBD = "jdbc:mysql://localhost:3306/" + bd;
    public static String user = "root";
    public static String passwd = "";
    public static Connection conn;
    public static GUIInsertarDatos guiInsertar;
    public static GUIBorrarDatos guiBorrar;
    public static GUIModificarDatos guiActualizar;
    //Los archivos externos que necesite el proyecto MAVEN deben de estar en src/main/resources.
    //Entonces para las imágenes creamos una carpeta resources/images
    //Luego tenemos que cargar la imagen como un recurso con el meétodo getResource(URL)
    private URL imagenURL;

    public EjemploCRUD() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setTitle("Primer ejemplo JDBC"); 
        this.setResizable(false);

        //ASIGNAMOS LA IMAGEN A LA JLABEL
        this.imagenURL = this.getClass().getResource("/images/imagen_inicial.png");
        //a)
//        this.jLabel1.setIcon(new ImageIcon(imagenURL));
        //PARA QUE QUEDE LA IMAGEN ESCALADA AL TAMAÑO DE LA JLABEL
        //b)
        ImageIcon imagen = new ImageIcon(imagenURL);              
        Image imagenEscalada=imagen.getImage().getScaledInstance(this.jLabel1.getWidth(),this.jLabel1.getHeight(), Image.SCALE_DEFAULT);
        this.jLabel1.setIcon(new ImageIcon(imagenEscalada));
        
        this.setLocationRelativeTo(null);  
    }

    public Connection abrirConexion() {
        try {
            return DriverManager.getConnection(urlBD, user, passwd);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con BD",
                    "Conexion BD", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuBD = new javax.swing.JMenu();
        jMenuItemConectar = new javax.swing.JMenuItem();
        jMenuCRUD = new javax.swing.JMenu();
        jMenuItemSekect = new javax.swing.JMenuItem();
        jMenuItemInsert = new javax.swing.JMenuItem();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenu3App = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 250));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 140));

        jMenuBD.setText("BD");

        jMenuItemConectar.setText("Conectar");
        jMenuItemConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConectarActionPerformed(evt);
            }
        });
        jMenuBD.add(jMenuItemConectar);

        jMenuBar.add(jMenuBD);

        jMenuCRUD.setText("CRUD");

        jMenuItemSekect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSekect.setText("Select");
        jMenuItemSekect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSekectActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuItemSekect);

        jMenuItemInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemInsert.setText("Insert");
        jMenuItemInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuItemInsert);

        jMenuItemUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUpdate.setText("Update");
        jMenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuItemUpdate);

        jMenuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemDelete.setText("Delete");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuItemDelete);

        jMenuBar.add(jMenuCRUD);

        jMenu3App.setText("Aplicación");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu3App.add(jMenuItemSalir);

        jMenuBar.add(jMenu3App);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConectarActionPerformed
        conn = abrirConexion();
        if (conn != null) {
            JOptionPane.showMessageDialog(this, "Conexión realizada con exito",
                    "Conexion '" + bd + "'", JOptionPane.PLAIN_MESSAGE);
            this.jMenuBD.setEnabled(false);
        }

    }//GEN-LAST:event_jMenuItemConectarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        try {
            conn.close();
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cerrar conexión con BD",
                    "Desconexion BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemSekectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSekectActionPerformed
        try {
            //1.abrir conexion
            conn = DriverManager.getConnection(urlBD, user, passwd);
            //2.ejecutamos consulta SELECT
            String sql = "select * from tabla_a";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                //procesamos la fila actual del conjunto de filas
                int a1 = rs.getInt("a1");
                String a2 = rs.getString("a2");
                double a3 = rs.getDouble("a3");
                Date a4 = rs.getDate("a4");
                //mostramos la fila por consola
                System.out.printf("%d -- %s -- %.2f -- %s %n", a1, a2, a3, a4);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con BD",
                    "Error BD", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        } finally {
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al cerrar BD",
                        "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_jMenuItemSekectActionPerformed

    private void jMenuItemInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertActionPerformed
        //abrimos la ventana para introducir los nuevos datos
        guiInsertar = new GUIInsertarDatos(this, true);
        guiInsertar.setVisible(true);

    }//GEN-LAST:event_jMenuItemInsertActionPerformed

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
        //abrimos la ventana para elegir el registro a borrar en la BD
        guiBorrar = new GUIBorrarDatos(this, true);
        guiBorrar.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void jMenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateActionPerformed
        //abrimos la ventana para elegir el registro a modificiar en la BD
        guiActualizar = new GUIModificarDatos(this, true);
        guiActualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3App;
    private javax.swing.JMenu jMenuBD;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCRUD;
    private javax.swing.JMenuItem jMenuItemConectar;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemInsert;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSekect;
    private javax.swing.JMenuItem jMenuItemUpdate;
    // End of variables declaration//GEN-END:variables
}
