/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicioAgenda;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author jovcubni
 */
public class AgendaContacto extends javax.swing.JFrame {
    public Contacto [] Agenda = new Contacto[3];
    public Contacto cont = new Contacto();

    /**
     * Creates new form AgendaContacto
     */
    public AgendaContacto() {
        initComponents();
        seting();
        
    }
    
    private void seting(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoBusqueda = new javax.swing.JTextField();
        BotonBuscarXNombre = new javax.swing.JButton();
        BotonBuscarXNumero = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonAñadir = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonVerContactos = new javax.swing.JButton();
        BotonElimianrTodo = new javax.swing.JButton();
        BotonModificarContacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonBuscarXNombre.setText("🔎 Nombre");
        BotonBuscarXNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarXNombreActionPerformed(evt);
            }
        });

        BotonBuscarXNumero.setText("🔎 Numero");
        BotonBuscarXNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarXNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBuscarXNombre)
                    .addComponent(BotonBuscarXNumero))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonBuscarXNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(BotonBuscarXNumero))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonAñadir.setText("🖊Añadir contacto");
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        BotonBorrar.setText("🗑 Borrar contacto");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonVerContactos.setText("👁 Ver Contactos");
        BotonVerContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerContactosActionPerformed(evt);
            }
        });

        BotonElimianrTodo.setText("❌ Vaciar agenda");
        BotonElimianrTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElimianrTodoActionPerformed(evt);
            }
        });

        BotonModificarContacto.setText("Modificar contacto");
        BotonModificarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonVerContactos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonElimianrTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(BotonModificarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BotonAñadir)
                .addGap(18, 18, 18)
                .addComponent(BotonBorrar)
                .addGap(18, 18, 18)
                .addComponent(BotonVerContactos)
                .addGap(18, 18, 18)
                .addComponent(BotonElimianrTodo)
                .addGap(18, 18, 18)
                .addComponent(BotonModificarContacto)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
      String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre:");
      if (nombre== null)
          JOptionPane.showMessageDialog(this, "No puede ser nulo","Advertencia",JOptionPane.INFORMATION_MESSAGE);
      String tele = JOptionPane.showInputDialog(this, "Ingrese el número:");
      if (tele == null)
          JOptionPane.showMessageDialog(this, "No puede ser nulo","Advertencia",JOptionPane.INFORMATION_MESSAGE);
      
        int telefono = Integer.parseInt(tele);
        if (telefono<0&& telefono>999999999)
              JOptionPane.showMessageDialog(this, "Fuera de rango ","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        
        for (int i = 0; i < Agenda.length; i++) {
            if (Agenda[i] == null) {
                Agenda[i] = new Contacto(i + 1, nombre, telefono);
                JOptionPane.showMessageDialog(this, "Contacto añadido con éxito: " + Agenda[i].toString());
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "La agenda está llena. No se puede añadir más contactos.");
    
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void BotonVerContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerContactosActionPerformed
        boolean hayContactos = false;
        for (Contacto contacto : Agenda) {
            if (contacto != null) {
                hayContactos = true;
                JOptionPane.showMessageDialog(this, contacto.toString(), "Contacto", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        if (!hayContactos) {
            JOptionPane.showMessageDialog(this, "Primero tienes que añadir contactos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonVerContactosActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        boolean hayContactos = false;
        boolean seBorro=false;
        for (Contacto contacto : Agenda) {
            if (contacto != null) {
                hayContactos = true;
                
            }
        }if (!hayContactos) {
            JOptionPane.showMessageDialog(this, "Primero tienes que añadir contactos", "Error", JOptionPane.ERROR_MESSAGE);
        }else  {
           String input = JOptionPane.showInputDialog(this, "Pon el Id que desa borrar");
           if (!input.isEmpty()){
               int aBorrar = Integer.parseInt(input);
                if (aBorrar>=1 || aBorrar<=Agenda.length ){
                     for (int i=0;i<Agenda.length;i++){
                         if (cont.getId()==aBorrar && seBorro==false){
                             int confirmacion = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres eliminar a "+ Agenda[i]);

                             if (confirmacion==0){
                                 Agenda[i]=null;
                                 JOptionPane.showMessageDialog(this, "Contacto eliminado correctamente.");
                                 seBorro=true;

                             }
                             else
                                 JOptionPane.showMessageDialog(this, "Operación cancelada.");
                          break;
                         }
                     }
                }else
                JOptionPane.showMessageDialog(this, "Fuera de rango","Advertencia",JOptionPane.INFORMATION_MESSAGE);
           } else
           JOptionPane.showMessageDialog(this, "No puede ser nulo","Advertencia",JOptionPane.INFORMATION_MESSAGE);
           
          //  System.out.println(Arrays.toString(Agenda[aBorrar]));
        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonBuscarXNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarXNombreActionPerformed
        // TODO add your handling code here:
        String nombreABuscar= TextoBusqueda.getText();
        boolean encontrado = false;
        if (nombreABuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (int i=0;i<Agenda.length;i++){
        
                if (Agenda[i].getNombre().equalsIgnoreCase(nombreABuscar)) {
                JOptionPane.showMessageDialog(this, Agenda[i].toString());
                encontrado=true;
                
                break;
            }
            break;
        }if (!encontrado)
        JOptionPane.showMessageDialog(this, "No encontrado", "Error busqueda",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_BotonBuscarXNombreActionPerformed

    private void BotonBuscarXNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarXNumeroActionPerformed
        // TODO add your handling code here:
         String numeroBusca= TextoBusqueda.getText();
        boolean encontrado = false;
        if (numeroBusca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int numeroABuscar = Integer.parseInt(numeroBusca);
        for (int i=0;i<Agenda.length;i++){
        
                if (Agenda[i].getTelefono()== numeroABuscar) {
                JOptionPane.showMessageDialog(this, Agenda[i].toString());
                encontrado=true;
                
                break;
            }
            break;
        }if (!encontrado)
        JOptionPane.showMessageDialog(this, "No encontrado", "Error busqueda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonBuscarXNumeroActionPerformed

    private void BotonElimianrTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElimianrTodoActionPerformed
        // TODO add your handling code here:
        boolean hayContactos = false;
        boolean seBorro=false;
        for (Contacto contacto : Agenda) {
            if (contacto != null) 
                hayContactos = true;
        }        
            
        if (!hayContactos){ 
            JOptionPane.showMessageDialog(this, "Ya esta bacia", "Info", JOptionPane.INFORMATION_MESSAGE);
        }else{ 
          int confirmacion = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres elimir todos los contactos");
            if (confirmacion==0){
                Agenda=null;
                JOptionPane.showMessageDialog(this, "Contacto eliminado correctamente.");
                seBorro=true;
            }else{
            JOptionPane.showMessageDialog(this, "Operación cancelada.");
            }
        }             
                
    }//GEN-LAST:event_BotonElimianrTodoActionPerformed

    private void BotonModificarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarContactoActionPerformed
        // TODO add your handling code here:
        boolean hayContactos = false;
        boolean seEdito=false;
        for (Contacto contacto : Agenda) {
            if (contacto != null) {
                hayContactos = true;
                
            }
        }if (!hayContactos) {
            JOptionPane.showMessageDialog(this, "Primero tienes que añadir contactos", "Error", JOptionPane.ERROR_MESSAGE);
        }else  {
           String input = JOptionPane.showInputDialog(this, "Pon el Id que desas editar");
           if (!input.isEmpty()){
               int aEditar = Integer.parseInt(input);
                if (aEditar>=1 || aEditar<=Agenda.length ){
                     for (int i=0;i<Agenda.length;i++){
                         if (cont.getId()==aEditar && seEdito==false){
                            Agenda[i].setNombre(JOptionPane.showInputDialog(this, "Nuevo nombre ("+Agenda[i].getNombre()+")"));
                            String telef =(JOptionPane.showInputDialog(this, "Nuevo telefono ("+Agenda[i].getTelefono()+")"));
                            Agenda[i].setTelefono(Integer.parseInt(telef));
                            seEdito= true;
                         }
                     }
                }else
                JOptionPane.showMessageDialog(this, "Fuera de rango","Advertencia",JOptionPane.INFORMATION_MESSAGE);
           } else
           JOptionPane.showMessageDialog(this, "No puede ser nulo","Advertencia",JOptionPane.INFORMATION_MESSAGE);
           
          //  System.out.println(Arrays.toString(Agenda[aBorrar]));
        }        
    }//GEN-LAST:event_BotonModificarContactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscarXNombre;
    private javax.swing.JButton BotonBuscarXNumero;
    private javax.swing.JButton BotonElimianrTodo;
    private javax.swing.JButton BotonModificarContacto;
    private javax.swing.JButton BotonVerContactos;
    private javax.swing.JTextField TextoBusqueda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
